#source 'https://github.com/CocoaPods/Specs'
# Uncomment this line to define a global platform for your project
platform :ios, '13'
# Uncomment this line if you're using Swift
use_frameworks!


def commom_pods
  
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'IQKeyboardManager'
  pod 'UITextView+Placeholder'
  pod 'KMNavigationBarTransition'
  pod 'SDCycleScrollView'
  pod 'SVProgressHUD'
  pod 'Toast'
  pod 'MMPopupView-Enhanced'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'SDAutoLayout', '2.2.0'

  #高德地图
  pod 'AMap3DMap'
  pod 'AMapSearch'
  pod 'AMapLocation'
  
  #二维码相关
  pod 'LBXScan/LBXNative','~> 2.5.1'
  pod 'LBXScan/LBXZXing','~> 2.5.1'
  pod 'LBXScan/UI','~> 2.5.1'
  
  #声网
  pod 'AgoraRtcEngine_iOS'
  
  #号码格式化
  pod 'libPhoneNumber-iOS'
  
  pod 'DZNEmptyDataSet'
  pod 'JXCategoryView'
  pod 'YYText'
  pod 'XinstallSDK'
  
  # 动画
#  pod 'lottie-ios', '~>3.5.0'
  
end

target 'BaseChat' do
  commom_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13'
    end
  end
end
